var CountryList = new Array();
var ISPList = new Array();
var ispPrtcl;
var ispContype;
var ispVPI;
var ispVCI;
var i=0;
CountryList[i++] = new Citem("Algeria", 3);
CountryList[i++] = new Citem("Australia", 12);
CountryList[i++] = new Citem("Bahrain", 1);
CountryList[i++] = new Citem("Chile", 2);
CountryList[i++] = new Citem("Colombia", 2);
CountryList[i++] = new Citem("Cyprus", 2);
CountryList[i++] = new Citem("Egypt", 18);
CountryList[i++] = new Citem("Indonesia", 7);
CountryList[i++] = new Citem("Iran", 16);
CountryList[i++] = new Citem("Israel", 1);
CountryList[i++] = new Citem("Jordan", 5);
CountryList[i++] = new Citem("Japan", 15);
CountryList[i++] = new Citem("Korea", 4);
CountryList[i++] = new Citem("KSA", 16);
CountryList[i++] = new Citem("Kuwait", 6);
CountryList[i++] = new Citem("Malaysia", 5);
CountryList[i++] = new Citem("Moroco", 1);
CountryList[i++] = new Citem("New Zealand", 2);
CountryList[i++] = new Citem("Oman", 1);
CountryList[i++] = new Citem("Pakistan", 12);
CountryList[i++] = new Citem("Palestine", 1);
CountryList[i++] = new Citem("Peru", 1);
CountryList[i++] = new Citem("Philippines", 4);
CountryList[i++] = new Citem("Qatar", 1);
CountryList[i++] = new Citem("Saudi Arabia", 1);
CountryList[i++] = new Citem("Singapore", 4);
CountryList[i++] = new Citem("Syria", 20);
CountryList[i++] = new Citem("Thailand", 9);
CountryList[i++] = new Citem("Tunisia", 2);
CountryList[i++] = new Citem("Turkey", 2);
CountryList[i++] = new Citem("Vietnam", 15);
CountryList[i++] = new Citem("UAE", 4);
CountryList[i++] = new Citem("Yemen", 2);
CountryList[i++] = new Citem("Russia", 30);
i = 0;
ISPList[i++] = new ISPitem("Algeria", "Fawri", "PPPoE", "LLC", "0", "38");
ISPList[i++] = new ISPitem("Algeria", "Anis", "PPPoE", "LLC", "0", "35");
ISPList[i++] = new ISPitem("Algeria", "Easy", "PPPoE", "LLC", "0", "35");
ISPList[i++] = new ISPitem("Australia", "AAPT", "PPPoE", "LLC", "8", "35");
ISPList[i++] = new ISPitem("Australia", "Dodo Internet", "PPPoE", "LLC", "8", "35");
ISPList[i++] = new ISPitem("Australia", "Internode", "PPPoE", "LLC", "8", "35");
ISPList[i++] = new ISPitem("Australia", "iinet", "PPPoE", "LLC", "8", "35");
ISPList[i++] = new ISPitem("Australia", "iPrimus", "PPPoE", "LLC", "8", "35");
ISPList[i++] = new ISPitem("Australia", "Netspace", "PPPoE", "LLC", "8", "35");
ISPList[i++] = new ISPitem("Australia", "Optus", "PPPoE", "LLC", "8", "35");
ISPList[i++] = new ISPitem("Australia", "OzEmail", "PPPoE", "LLC", "8", "35");
ISPList[i++] = new ISPitem("Australia", "Pacific Internet", "PPPoE", "LLC", "8", "35");
ISPList[i++] = new ISPitem("Australia", "TelPacific", "PPPoE", "LLC", "8", "35");
ISPList[i++] = new ISPitem("Australia", "Telstra BigPond", "PPPoE", "LLC", "8", "35");
ISPList[i++] = new ISPitem("Australia", "TGP", "PPPoE", "LLC", "8", "35");
ISPList[i++] = new ISPitem("Bahrain", "BATELCO", "PPPoE", "VC-Mux", "8", "35");
ISPList[i++] = new ISPitem("Chile", "Telefonica Chile(Bridge)", "Bridge", "LLC", "8", "32");
ISPList[i++] = new ISPitem("Chile", "Telefonica Chile(PPPoE)", "PPPoE", "LLC", "8", "34");
ISPList[i++] = new ISPitem("Colombia", "Emcali(PPPoA)", "PPPoA", "VC-Mux", "2", "35");
ISPList[i++] = new ISPitem("Colombia", "Emcali(PPPoE)", "PPPoE", "LLC", "2", "35");
ISPList[i++] = new ISPitem("Cyprus", "OTENET", "PPPoE", "LLC", "8", "35");
ISPList[i++] = new ISPitem("Cyprus", "CYTA", "PPPoA", "VC-Mux", "8", "35");
ISPList[i++] = new ISPitem("Egypt", "EGYNET(PPPoA)", "PPPoA", "VC-Mux", "8", "35");
ISPList[i++] = new ISPitem("Egypt", "EGYNET(IPoA)", "Static IP", "LLC", "8", "35");
ISPList[i++] = new ISPitem("Egypt", "EGYNET(PPPoE)", "PPPoE", "LLC", "0", "35");
ISPList[i++] = new ISPitem("Egypt", "LINKdotNET(PPPoA)", "PPPoA", "VC-Mux", "0", "35");
ISPList[i++] = new ISPitem("Egypt", "LINKdotNET(IPoA)", "Static IP", "LLC", "0", "35");
ISPList[i++] = new ISPitem("Egypt", "LINKdotNET(PPPoE)", "PPPoE", "LLC", "0", "35");
ISPList[i++] = new ISPitem("Egypt", "Nour(PPPoA)", "PPPoA", "VC-Mux", "8", "35");
ISPList[i++] = new ISPitem("Egypt", "Nour(IPoA)", "Static IP", "LLC", "8", "35");
ISPList[i++] = new ISPitem("Egypt", "TeData(PPPoA)", "PPPoA", "VC-Mux", "0", "35");
ISPList[i++] = new ISPitem("Egypt", "TeData(IPoA)", "Static IP", "LLC", "0", "35");
ISPList[i++] = new ISPitem("Egypt", "TeData(PPPoE)", "PPPoE", "LLC", "0", "35");
ISPList[i++] = new ISPitem("Egypt", "Vodafone(PPPoA)", "PPPoA", "VC-Mux", "0", "35");
ISPList[i++] = new ISPitem("Egypt", "Vodafone(IPoA)", "Static IP", "LLC", "0", "35");
ISPList[i++] = new ISPitem("Egypt", "Vodafone(PPPoE)", "PPPoE", "LLC", "0", "35");
ISPList[i++] = new ISPitem("Egypt", "Etisalat(PPPoA)", "PPPoA", "VC-Mux", "0", "35");
ISPList[i++] = new ISPitem("Egypt", "Etisalat(IPoA)", "Static IP", "LLC", "0", "35");
ISPList[i++] = new ISPitem("Egypt", "Etisalat(PPPoE)", "PPPoE", "LLC", "0", "35");
ISPList[i++] = new ISPitem("Egypt", "Nile on Line", "PPPoE", "LLC", "0", "35");
ISPList[i++] = new ISPitem("Indonesia", "PT Telkom DIVRE 1 (Sumatra)", "PPPoE", "LLC", "0", "35");
ISPList[i++] = new ISPitem("Indonesia", "PT Telkom DIVRE 2 (Jakarta) Alcatel", "PPPoA", "LLC", "8", "35");
ISPList[i++] = new ISPitem("Indonesia", "PT Telkom DIVRE 2 (Jakarta) Siemens", "PPPoA", "VC-Mux", "1", "33");
ISPList[i++] = new ISPitem("Indonesia", "PT Telkom DIVRE 3 (West Java)", "PPPoA", "VC-Mux", "1", "33");
ISPList[i++] = new ISPitem("Indonesia", "PT Telkom DIVRE 4 (Central Java)", "PPPoE", "LLC", "8", "35");
ISPList[i++] = new ISPitem("Indonesia", "PT Telkom DIVRE 5 (East Java)", "PPPoE", "LLC", "0", "35");
ISPList[i++] = new ISPitem("Indonesia", "PT Telkom DIVRE 7 (East Indonesia)", "PPPoE", "LLC", "0", "35");
ISPList[i++] = new ISPitem("Iran", "Asia Tec", "PPPoE", "LLC", "0", "35");
ISPList[i++] = new ISPitem("Iran", "Daade Gostar e Novin", "PPPoE", "LLC", "0", "33");
ISPList[i++] = new ISPitem("Iran", "DATAK-Telecom", "PPPoE", "LLC", "0", "35");
ISPList[i++] = new ISPitem("Iran", "Laser", "PPPoE", "LLC", "0", "35");
ISPList[i++] = new ISPitem("Iran", "Neda Rayane", "Bridge", "LLC", "0", "33");
ISPList[i++] = new ISPitem("Iran", "Pars OnLine", "PPPoE", "LLC", "0", "35");
ISPList[i++] = new ISPitem("Iran", "Sabanet", "PPPoE", "LLC", "0", "35");
ISPList[i++] = new ISPitem("Iran", "Shatel", "PPPoE", "LLC", "0", "35");
ISPList[i++] = new ISPitem("Iran", "IRAN TCT", "PPPoE", "LLC", "0", "35");
ISPList[i++] = new ISPitem("Iran", "IRAN TCT 2", "PPPoE", "LLC", "8", "81");
ISPList[i++] = new ISPitem("Iran", "Shahrad", "PPPoE", "LLC", "0", "35");
ISPList[i++] = new ISPitem("Iran", "Oracle", "PPPoE", "LLC", "0", "35");
ISPList[i++] = new ISPitem("Iran", "Afranet", "PPPoE", "LLC", "0", "35");
ISPList[i++] = new ISPitem("Iran", "Pishgaman", "PPPoE", "LLC", "0", "35");
ISPList[i++] = new ISPitem("Iran", "Mahannet", "PPPoE", "LLC", "0", "35");
ISPList[i++] = new ISPitem("Iran", "Sepanta", "PPPoE", "LLC", "0", "35");
ISPList[i++] = new ISPitem("Israel", "Bezeq", "PPPoE", "LLC", "8", "48");
ISPList[i++] = new ISPitem("Jordan", "Batelco-Jordan (PPPoE LLC)", "PPPoE", "LLC", "8", "35");
ISPList[i++] = new ISPitem("Jordan", "Batelco-Jordan (PPPoE VC-Mux)", "PPPoE", "VC-Mux", "8", "35");
ISPList[i++] = new ISPitem("Jordan", "Cyberia", "PPPoE", "LLC", "8", "35");
ISPList[i++] = new ISPitem("Jordan", "Orange Internet", "PPPoE", "LLC", "8", "35");
ISPList[i++] = new ISPitem("Jordan", "Wanadoo", "PPPoE", "LLC", "8", "35");
ISPList[i++] = new ISPitem("Japan", "ACCA", "PPPoA", "LLC", "0", "35");
ISPList[i++] = new ISPitem("Japan", "CTnet", "PPPoA", "LLC", "0", "32");
ISPList[i++] = new ISPitem("Japan", "DION (KDDI)", "PPPoA", "LLC", "0", "35");
ISPList[i++] = new ISPitem("Japan", "eAccess", "PPPoE", "LLC", "0", "32");
ISPList[i++] = new ISPitem("Japan", "eAccess (PPPoA)", "PPPoA", "VC-Mux", "0", "32");
ISPList[i++] = new ISPitem("Japan", "FLET's ADSL (NTT)", "PPPoE", "LLC", "0", "32");
ISPList[i++] = new ISPitem("Japan", "HTnet", "PPPoA", "LLC", "0", "32");
ISPList[i++] = new ISPitem("Japan", "KCN", "PPPoA", "VC-Mux", "0", "32");
ISPList[i++] = new ISPitem("Japan", "Nagoya", "PPPoE", "LLC", "0", "32");
ISPList[i++] = new ISPitem("Japan", "OCN", "PPPoE", "LLC", "0", "35");
ISPList[i++] = new ISPitem("Japan", "OCN (J-DSL Personal)", "PPPoA", "VC-Mux", "0", "32");
ISPList[i++] = new ISPitem("Japan", "OCN (J-DSL Business)", "PPPoA", "VC-Mux", "0", "33");
ISPList[i++] = new ISPitem("Japan", "RMC", "Dynamic IP", "LLC", "0", "35");
ISPList[i++] = new ISPitem("Japan", "T-com", "PPPoA", "VC-Mux", "0", "32");
ISPList[i++] = new ISPitem("Japan", "Yahoo!BB (SoftBankBB)", "Dynamic IP", "LLC", "0", "35");
ISPList[i++] = new ISPitem("Korea", "Hanaro Telecom(PPPoE)", "PPPoE", "LLC", "0", "67");
ISPList[i++] = new ISPitem("Korea", "Hanaro Telecom(PPPoA)", "PPPoA", "VC-Mux", "0", "67");
ISPList[i++] = new ISPitem("Korea", "KT(Korea Telecom)(PPPoE)", "PPPoE", "LLC", "0", "32");
ISPList[i++] = new ISPitem("Korea", "KT(Korea Telecom)(PPPoA)", "PPPoA", "LLC", "0", "32");
ISPList[i++] = new ISPitem("KSA", "Atheer", "PPPoE", "LLC", "0", "35");
ISPList[i++] = new ISPitem("KSA", "Awalnet", "PPPoE", "LLC", "0", "35");
ISPList[i++] = new ISPitem("KSA", "Cyberia", "PPPoE", "LLC", "0", "35");
ISPList[i++] = new ISPitem("KSA", "Nesma", "PPPoE", "LLC", "0", "35");
ISPList[i++] = new ISPitem("KSA", "Sahara", "PPPoE", "LLC", "0", "35");
ISPList[i++] = new ISPitem("KSA", "Saudinet", "PPPoE", "LLC", "0", "35");
ISPList[i++] = new ISPitem("KSA", "Shabakah", "PPPoE", "LLC", "0", "35");
ISPList[i++] = new ISPitem("KSA", "Zajil", "PPPoE", "LLC", "0", "35");
ISPList[i++] = new ISPitem("KSA", "Zajoul", "PPPoE", "LLC", "0", "35");
ISPList[i++] = new ISPitem("KSA", "Digi Net", "PPPoE", "LLC", "0", "35");
ISPList[i++] = new ISPitem("KSA", "ICC", "PPPoE", "LLC", "0", "35");
ISPList[i++] = new ISPitem("KSA", "nour.net.sa", "PPPoE", "LLC", "0", "35");
ISPList[i++] = new ISPitem("KSA", "saudionline.com.sa", "PPPoE", "LLC", "0", "35");
ISPList[i++] = new ISPitem("KSA", "sol.net.sa", "PPPoE", "LLC", "0", "35");
ISPList[i++] = new ISPitem("KSA", "suhuf.net.sa", "PPPoE", "LLC", "0", "35");
ISPList[i++] = new ISPitem("KSA", "arabcircle.net.sa", "PPPoE", "LLC", "0", "35");
ISPList[i++] = new ISPitem("Kuwait", "KEMS", "PPPoE", "LLC", "0", "35");
ISPList[i++] = new ISPitem("Kuwait", "Gulfnet", "PPPoA", "LLC", "0", "33");
ISPList[i++] = new ISPitem("Kuwait", "Fasttelco", "PPPoE", "VC-Mux", "1", "100");
ISPList[i++] = new ISPitem("Kuwait", "QualityNet", "PPPoA", "VC-Mux", "8", "35");
ISPList[i++] = new ISPitem("Kuwait", "United(Corporate)", "PPPoE", "LLC", "0", "32");
ISPList[i++] = new ISPitem("Kuwait", "United(Home)", "PPPoE", "LLC", "0", "33");
ISPList[i++] = new ISPitem("Malaysia", "Maxis (Maxis PPPoA)", "PPPoA", "LLC", "0", "35");
ISPList[i++] = new ISPitem("Malaysia", "Maxis (Maxis PPPoE)", "PPPoE", "LLC", "0", "35");
ISPList[i++] = new ISPitem("Malaysia", "Streamyx (Telecom Malaysia - PPPoE)", "PPPoE", "LLC", "0", "35");
ISPList[i++] = new ISPitem("Malaysia", "Streamyx (Telecom Malaysia - PPPoA)", "PPPoA", "LLC", "0", "35");
ISPList[i++] = new ISPitem("Malaysia", "Time", "PPPoE", "LLC", "0", "35");
ISPList[i++] = new ISPitem("Moroco", "MAROC Telecom(IAM)", "PPPoE", "LLC", "8", "35");
ISPList[i++] = new ISPitem("New Zealand", "IHUG", "PPPoA", "VC-Mux", "0", "100");
ISPList[i++] = new ISPitem("New Zealand", "Telecom Xtra", "PPPoA", "VC-Mux", "0", "100");
ISPList[i++] = new ISPitem("Oman", "Oman Tel", "PPPoE", "LLC", "0", "35");
ISPList[i++] = new ISPitem("Pakistan", "CyberNet", "PPPoE", "LLC", "0", "35");
ISPList[i++] = new ISPitem("Pakistan", "Cubexs", "PPPoE", "LLC", "0", "35");
ISPList[i++] = new ISPitem("Pakistan", "Dancom", "PPPoE", "LLC", "8", "35");
ISPList[i++] = new ISPitem("Pakistan", "LinkDotNet", "PPPoE", "LLC", "0", "35");
ISPList[i++] = new ISPitem("Pakistan", "GerrysNet", "PPPoE", "LLC", "0", "35");
ISPList[i++] = new ISPitem("Pakistan", "Micronet", "PPPoE", "LLC", "0", "35");
ISPList[i++] = new ISPitem("Pakistan", "MicroNetBroadband", "PPPoE", "LLC", "1", "32");
ISPList[i++] = new ISPitem("Pakistan", "MultiNet", "PPPoE", "LLC", "0", "35");
ISPList[i++] = new ISPitem("Pakistan", "PTCL", "PPPoE", "LLC", "0", "103");
ISPList[i++] = new ISPitem("Pakistan", "PTCL", "PPPoE", "LLC", "8", "81");
ISPList[i++] = new ISPitem("Pakistan", "PAKNet", "PPPoE", "LLC", "0", "35");
ISPList[i++] = new ISPitem("Pakistan", "WolNet", "PPPoE", "LLC", "0", "35");
ISPList[i++] = new ISPitem("Palestine", "PalTel/Hadara", "PPPoE", "LLC", "8", "35");
ISPList[i++] = new ISPitem("Peru", "Telefonica", "PPPoE", "LLC", "8", "60");
ISPList[i++] = new ISPitem("Philippines", "Globe", "PPPoA", "VC-Mux", "0", "35");
ISPList[i++] = new ISPitem("Philippines", "PLDT (Manila)", "PPPoE", "LLC", "0", "100");
ISPList[i++] = new ISPitem("Philippines", "PLDT (Provincial)", "PPPoE", "LLC", "0", "35");
ISPList[i++] = new ISPitem("Philippines", "Bayantel", "PPPoE", "LLC", "0", "33");
ISPList[i++] = new ISPitem("Qatar", "QTEL", "PPPoE", "LLC", "8", "35");
ISPList[i++] = new ISPitem("Saudi Arabia", "Saudi Telecom", "PPPoE", "LLC", "0", "35");
ISPList[i++] = new ISPitem("Singapore", "Pacific Internet(PPPoA)", "PPPoA", "VC-Mux", "0", "100");
ISPList[i++] = new ISPitem("Singapore", "Pacific Internet(PPPoE)", "PPPoE", "LLC", "0", "100");
ISPList[i++] = new ISPitem("Singapore", "Singnet Broad Band(PPPoA)", "PPPoA", "VC-Mux", "0", "100");
ISPList[i++] = new ISPitem("Singapore", "Singnet Broad Band(PPPoE)", "PPPoE", "LLC", "0", "100");
ISPList[i++] = new ISPitem("Syria", "Syrian Telecom-1", "PPPoE", "LLC", "0", "33");
ISPList[i++] = new ISPitem("Syria", "Syrian Telecom-2", "PPPoA", "LLC", "0", "35");
ISPList[i++] = new ISPitem("Syria", "TARASSUL", "PPPoE", "LLC", "8", "35");
ISPList[i++] = new ISPitem("Syria", "SAMA", "PPPoE", "LLC", "8", "35");
ISPList[i++] = new ISPitem("Syria", "SAWA", "PPPoE", "LLC", "8", "35");
ISPList[i++] = new ISPitem("Syria", "I-NET", "PPPoE", "LLC", "8", "35");
ISPList[i++] = new ISPitem("Syria", "LEMA", "PPPoE", "LLC", "8", "35");
ISPList[i++] = new ISPitem("Syria", "NAAS", "PPPoE", "LLC", "8", "35");
ISPList[i++] = new ISPitem("Syria", "SCS-NET", "PPPoE", "LLC", "8", "35");
ISPList[i++] = new ISPitem("Syria", "AYA", "PPPoE", "LLC", "8", "35");
ISPList[i++] = new ISPitem("Syria", "VIEW", "PPPoE", "LLC", "8", "35");
ISPList[i++] = new ISPitem("Syria", "E-LCOM", "PPPoE", "LLC", "8", "35");
ISPList[i++] = new ISPitem("Syria", "OMNIYA", "PPPoE", "LLC", "8", "35");
ISPList[i++] = new ISPitem("Syria", "RUNNET", "PPPoE", "LLC", "8", "35");
ISPList[i++] = new ISPitem("Syria", "Asra3net", "PPPoE", "LLC", "8", "35");
ISPList[i++] = new ISPitem("Syria", "SMA", "PPPoE", "LLC", "8", "35");
ISPList[i++] = new ISPitem("Syria", "MTN", "PPPoE", "LLC", "8", "35");
ISPList[i++] = new ISPitem("Syria", "190", "PPPoE", "LLC", "0", "30");
ISPList[i++] = new ISPitem("Syria", "zad", "PPPoE", "LLC", "8", "35");
ISPList[i++] = new ISPitem("Syria", "OTHERS", "PPPoE", "LLC", "8", "35");
ISPList[i++] = new ISPitem("Thailand", "3BB", "PPPoE", "LLC", "0", "33");
ISPList[i++] = new ISPitem("Thailand", "ADC : CS-Loxinfo:", "PPPoE", "LLC", "0", "35");
ISPList[i++] = new ISPitem("Thailand", "Samart", "PPPoE", "LLC", "0", "35");
ISPList[i++] = new ISPitem("Thailand", "TOT", "PPPoE", "LLC", "1", "32");
ISPList[i++] = new ISPitem("Thailand", "TRUE (Huawei)", "PPPoE", "LLC", "0", "100");
ISPList[i++] = new ISPitem("Thailand", "TT&T (Normal)", "PPPoE", "LLC", "0", "33");
ISPList[i++] = new ISPitem("Thailand", "TT&T (Hinet)", "PPPoE", "LLC", "0", "66");
ISPList[i++] = new ISPitem("Thailand", "Qnet", "PPPoE", "LLC", "0", "40");
ISPList[i++] = new ISPitem("Thailand", "UCOM", "PPPoE", "LLC", "0", "100");
ISPList[i++] = new ISPitem("Tunisia", "Tunet", "PPPoE", "LLC", "0", "35");
ISPList[i++] = new ISPitem("Tunisia", "Tunisiana", "PPPoE", "LLC", "0", "35");
ISPList[i++] = new ISPitem("Turkey", "TTNET(PPPoA)", "PPPoA", "VC-Mux", "8", "35");
ISPList[i++] = new ISPitem("Turkey", "TTNET(PPPoE)", "PPPoE", "LLC", "8", "35");
ISPList[i++] = new ISPitem("Vietnam", "VNPT_Internet_1", "PPPoE", "LLC", "0", "32");
ISPList[i++] = new ISPitem("Vietnam", "VNPT_Internet_2", "PPPoE", "LLC", "0", "35");
ISPList[i++] = new ISPitem("Vietnam", "VNPT_Internet_3", "PPPoE", "LLC", "8", "35");
ISPList[i++] = new ISPitem("Vietnam", "VNPT_IPTV_0", "Bridge", "LLC", "0", "34");
ISPList[i++] = new ISPitem("Vietnam", "VNPT_IPTV_1", "Bridge", "LLC", "0", "35");
ISPList[i++] = new ISPitem("Vietnam", "VNPT_IPTV_2", "Bridge", "LLC", "0", "36");
ISPList[i++] = new ISPitem("Vietnam", "VNPT_IPTV_4", "Bridge", "LLC", "2", "35");
ISPList[i++] = new ISPitem("Vietnam", "VNPT_IPTV_5", "Bridge", "LLC", "8", "36");
ISPList[i++] = new ISPitem("Vietnam", "VNPT_IPTV_6", "Bridge", "LLC", "8", "37");
ISPList[i++] = new ISPitem("Vietnam", "VIETTEL_Internet", "PPPoE", "LLC", "8", "35");
ISPList[i++] = new ISPitem("Vietnam", "VIETTEL_IPTV", "Bridge", "LLC", "8", "36");
ISPList[i++] = new ISPitem("Vietnam", "FPT_Internet", "PPPoE", "LLC", "0", "33");
ISPList[i++] = new ISPitem("Vietnam", "FPT_IPTV", "Bridge", "LLC", "8", "35");
ISPList[i++] = new ISPitem("Vietnam", "SPT_internet", "PPPoE", "LLC", "0", "33");
ISPList[i++] = new ISPitem("Vietnam", "Netnam_internet", "PPPoE", "LLC", "0", "33");
ISPList[i++] = new ISPitem("UAE", "Etisalat(PPPoA)", "PPPoA", "LLC", "0", "50");
ISPList[i++] = new ISPitem("UAE", "Etisalat(PPPoE)", "PPPoE", "LLC", "0", "50");
ISPList[i++] = new ISPitem("UAE", "Raya Telecom(PPPoA)", "PPPoA", "VC-Mux", "0", "35");
ISPList[i++] = new ISPitem("UAE", "Raya Telecom(Static IP)", "Static IP", "LLC", "8", "80");
ISPList[i++] = new ISPitem("Yemen", "Yemen Net(PPPoA)", "PPPoA", "VC-Mux", "8", "35");
ISPList[i++] = new ISPitem("Yemen", "Yemen Net(PPPoE)", "PPPoE", "LLC", "8", "35");
ISPList[i++] = new ISPitem("Russia", "AAA-internet (Rostov)", "PPPoE", "LLC", "0", "33");
ISPList[i++] = new ISPitem("Russia", "AgentstvoDelovoySvyazi", "Static IP", "LLC", "8", "35");
ISPList[i++] = new ISPitem("Russia", "Bashinformsvyaz UGTS", "PPPoE", "LLC", "8", "35");
ISPList[i++] = new ISPitem("Russia", "DalSvyaz", "Bridge", "LLC", "0", "35");
ISPList[i++] = new ISPitem("Russia", "Delovaya Set - Irkutsk", "Bridge", "LLC", "0", "35");
ISPList[i++] = new ISPitem("Russia", "Infoline", "PPPoE", "LLC", "2", "32");
ISPList[i++] = new ISPitem("Russia", "InformSvyaaz-Chernozemie", "PPPoE", "LLC", "0", "33");
ISPList[i++] = new ISPitem("Russia", "Intercon", "PPPoE", "LLC", "0", "33");
ISPList[i++] = new ISPitem("Russia", "Kominkom-Voronezh", "PPPoE", "LLC", "0", "33");
ISPList[i++] = new ISPitem("Russia", "Megapolis-Telecom", "PPPoE", "LLC", "8", "35");
ISPList[i++] = new ISPitem("Russia", "NIS (NN inform networks)", "Bridge", "LLC", "8", "35");
ISPList[i++] = new ISPitem("Russia", "Sandy", "Bridge", "LLC", "0", "33");
ISPList[i++] = new ISPitem("Russia", "Sibirtelecom Irkutskaya oblast", "PPPoE", "LLC", "0", "100");
ISPList[i++] = new ISPitem("Russia", "Stream", "PPPoE", "LLC", "1", "50");
ISPList[i++] = new ISPitem("Russia", "UralSvyazInform", "PPPoE", "LLC", "8", "35");
ISPList[i++] = new ISPitem("Russia", "UTK:Adygeya", "PPPoE", "LLC", "0", "35");
ISPList[i++] = new ISPitem("Russia", "UTK:Astrakhan", "PPPoE", "LLC", "0", "35");
ISPList[i++] = new ISPitem("Russia", "UTK:Kabardino-Balkariya", "PPPoE", "LLC", "0", "67");
ISPList[i++] = new ISPitem("Russia", "UTK:Karachaevo-Cherkesiya", "PPPoE", "LLC", "0", "35");
ISPList[i++] = new ISPitem("Russia", "UTK:Krasnodar", "PPPoE", "LLC", "0", "35");
ISPList[i++] = new ISPitem("Russia", "UTK:Sev.Osetiya(Alayniya)", "PPPoE", "LLC", "0", "35");
ISPList[i++] = new ISPitem("Russia", "UTK:Stavropol", "PPPoA", "LLC", "8", "35");
ISPList[i++] = new ISPitem("Russia", "UTK:Volgograd", "PPPoE", "LLC", "8", "35");
ISPList[i++] = new ISPitem("Russia", "VeresADSL", "PPPoE", "LLC", "10", "40");
ISPList[i++] = new ISPitem("Russia", "VolgaTelecom(Nijniy Novgorod)", "PPPoE", "LLC", "0", "33");
ISPList[i++] = new ISPitem("Russia", "VolgaTelecom(Samara)", "PPPoE", "LLC", "1", "100");
ISPList[i++] = new ISPitem("Russia", "VoronezhSvyazInform", "Static IP", "LLC", "10", "40");
ISPList[i++] = new ISPitem("Russia", "VostokTelecom", "Bridge", "LLC", "0", "35");
ISPList[i++] = new ISPitem("Russia", "WebPlus", "Static IP", "LLC", "1", "32");
ISPList[i++] = new ISPitem("Russia", "Webstream (Novosibirsk)", "PPPoE", "LLC", "0", "35");
function Citem(country, isps)
{
this.country = country;
this.isps = isps;
}
function ISPitem(country, ispname, protocol, contype, vpi, vci)
{
this.country = country;
this.ispname = ispname;
this.protocol = protocol;
this.contype = contype;
this.vpi = vpi;
this.vci = vci;
}
function changeISP(cb1, cb2)
{
var value = cb1.value;
cb2.options.length = 0;
cb2.options[0]=new Option("(Click to Select)", "-1");
if ((value == -1) || (value == -2)) {
cb2.options[1] = new Option("Others", "-2");
if ((value == -2))
cb2.selectedIndex = cb2.length - 1;
return;
}
var count =0;
for (i = 0; i < ISPList.length; i ++) {
if (CountryList[cb1.value].country == ISPList[i].country) {
cb2.options[count+1] = new Option(ISPList[i].ispname, i);
count ++;
}
if (count == CountryList[cb1.value].isps) {
break;
}
}
cb2.options[count + 1]=new Option("Others", "-2");
}
function createCountry(cb)
{
cb.options.length=0;
cb.options[0]=new Option("(Click to Select)", "-1");
var count =0;
for (i = 0; i < CountryList.length; i ++) {
cb.options[i+1]=new Option(CountryList[i].country, i);
count ++;
}
cb.options[count + 1]=new Option("Others", "-2");
}
function getISPDetails(cb)
{
var value = cb.value;
if ((value == -1) || (value == -2)) {
ispPrtcl = "";
ispVPI = "";
ispVCI = "";
ispContype = "";
return;
}
ispPrtcl = ISPList[cb.value].protocol;
ispContype = ISPList[cb.value].contype;
ispVPI = ISPList[cb.value].vpi;
ispVCI = ISPList[cb.value].vci;
}


